package com.kelio.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------




import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class ArrayOfClocking extends Vector<Clocking> implements KvmSerializable
{
    private transient java.lang.Object __source;

    public ArrayOfClocking()
    {
    }

    public ArrayOfClocking(int initialCapactiy)
    {
        super(initialCapactiy);
    }

    public ArrayOfClocking(java.util.Collection<Clocking> initialCapactiy)
    {
        super(initialCapactiy);
    }

    public void loadFromSoap(java.lang.Object inObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        __source=inObj;
        if(inObj instanceof SoapPrimitive){
            SoapPrimitive soapObject=(SoapPrimitive)inObj;
            int size = soapObject.getAttributeCount();
            for (int i0=0;i0< size;i0++)
            {
                java.lang.Object obj = soapObject.getAttribute(i0);
                if (obj!=null && obj instanceof AttributeContainer)
                {
                    AttributeContainer j =(AttributeContainer) soapObject.getAttribute(i0);
                    Clocking j1= (Clocking)__envelope.get(j, Clocking.class,false);
                    add(j1);
                }
            }

        } else {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0 = 0; i0 < size; i0++) {
                java.lang.Object obj = soapObject.getProperty(i0);
                if (obj != null && obj instanceof AttributeContainer) {
                    AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                    Clocking j1 = (Clocking) __envelope.get(j, Clocking.class, false);
                    add(j1);

                }
            }
        }
    }

    public java.lang.Object getSourceObject()
    {
        return __source;
    }
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, Hashtable arg1, PropertyInfo info) {
        info.name = "Clocking";
        info.type = Clocking.class;
    	info.namespace= "http://echange.service.open.bodet.com";
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

    
}