package com.kelio.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------




import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class ArrayOfAskedPopulationWithPeriod extends Vector<AskedPopulationWithPeriod> implements KvmSerializable
{
    private transient java.lang.Object __source;

    public ArrayOfAskedPopulationWithPeriod()
    {
    }

    public ArrayOfAskedPopulationWithPeriod(int initialCapactiy)
    {
        super(initialCapactiy);
    }

    public ArrayOfAskedPopulationWithPeriod(java.util.Collection<AskedPopulationWithPeriod> initialCapactiy)
    {
        super(initialCapactiy);
    }

    public void loadFromSoap(java.lang.Object inObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        __source=inObj;
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                java.lang.Object obj = soapObject.getProperty(i0);
                if (obj!=null && obj instanceof AttributeContainer)
                {
                    AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                    AskedPopulationWithPeriod j1= (AskedPopulationWithPeriod)__envelope.get(j, AskedPopulationWithPeriod.class,false);
                    add(j1);
                    
                }
            }
    }

    public java.lang.Object getSourceObject()
    {
        return __source;
    }
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, Hashtable arg1, PropertyInfo info) {
        info.name = "AskedPopulationWithPeriod";
        info.type = AskedPopulationWithPeriod.class;
    	info.namespace= "http://echange.service.open.bodet.com";
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

    
}