package com.kelio.webservice;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class AskedPopulationWithPeriod extends AskedPopulation implements KvmSerializable
{

    
    private java.util.Date endDate;
    
    private java.util.Date startDate;
    
    private Integer dateMode;
    
    private Integer endOffset;
    
    private Integer startOffset;
    
    public java.util.Date getEndDate()
    {
        return this.endDate;
    }
    
    public void setEndDate(java.util.Date value)
    {
        this.endDate = value;     
    }
    
    public java.util.Date getStartDate()
    {
        return this.startDate;
    }
    
    public void setStartDate(java.util.Date value)
    {
        this.startDate = value;     
    }
    
    public Integer getDateMode()
    {
        return this.dateMode;
    }
    
    public void setDateMode(Integer value)
    {
        this.dateMode = value;     
    }
    
    public Integer getEndOffset()
    {
        return this.endOffset;
    }
    
    public void setEndOffset(Integer value)
    {
        this.endOffset = value;     
    }
    
    public Integer getStartOffset()
    {
        return this.startOffset;
    }
    
    public void setStartOffset(Integer value)
    {
        this.startOffset = value;     
    }


    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);



    }

    @Override
    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("endDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.endDate = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.endDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("startDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.startDate = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.startDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("dateMode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.dateMode = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.dateMode = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("endOffset"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.endOffset = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.endOffset = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("startOffset"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.startOffset = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.startOffset = (Integer)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.endDate!=null? ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDate(this.endDate):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+1)
        {
            return this.startDate!=null? ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDate(this.startDate):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+2)
        {
            return this.dateMode!=null?this.dateMode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+3)
        {
            return this.endOffset!=null?this.endOffset:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+4)
        {
            return this.startOffset!=null?this.startOffset:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "endDate";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "startDate";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "dateMode";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "endOffset";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "startOffset";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
