package com.kelio.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------





import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.kxml2.kdom.Element;

import java.util.ArrayList;
import java.util.List;


public class ClockingServiceSoapBinding
{
    interface AGSIWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://192.168.0.18:8089/open/services/ClockingService";

    int timeOut=60000;
    private List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    private boolean enableLogging;

    IServiceEvents callback;

    public List< HeaderProperty> getHttpHeaders()
    {
        return this.httpHeaders;
    }
    
    public boolean getEnableLogging()
    {
        return this.enableLogging;
    }
    
    public void setEnableLogging(boolean value)
    {
        this.enableLogging=value;
    }
    

    
    public ClockingServiceSoapBinding(){}

    public ClockingServiceSoapBinding(IServiceEvents callback)
    {
        this.callback = callback;
    }
    public ClockingServiceSoapBinding(IServiceEvents callback, String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public ClockingServiceSoapBinding(IServiceEvents callback, String url, int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                String path=uri.getPath();
                if(uri.getQuery()!=null && uri.getQuery()!="")
                {
                    path+="?"+uri.getQuery();
                }
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, path, timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
            return envelope;
    }

    protected java.util.List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport , com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj, java.lang.Object source, String resultName, ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    
    
    public ArrayOfClocking exportCalculatedClockingsOnly(final ArrayOfAskedPopulationWithPeriod employeeList) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://echange.service.open.bodet.com","employeeList", ArrayOfAskedPopulationWithPeriod.class);
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "exportCalculatedClockingsOnly");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="employeeList";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(employeeList!=null?employeeList:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"exportedClockings",__envelope);
            }
        },"urn:exportCalculatedClockingsOnly",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult<ArrayOfClocking>> exportCalculatedClockingsOnlyAsync(final ArrayOfAskedPopulationWithPeriod employeeList)
    {
        return executeAsync(new Functions.IFunc<ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return exportCalculatedClockingsOnly( employeeList);
            }
        },"exportCalculatedClockingsOnly");
    }
    
    
    
    public ArrayOfClocking exportClockingsByDateForEmployeeList(final ArrayOfAskedEmployee employeeList) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://echange.service.open.bodet.com","employeeList", ArrayOfAskedEmployee.class);
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "exportClockingsByDateForEmployeeList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="employeeList";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(employeeList!=null?employeeList:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"exportedClockings",__envelope);
            }
        },"urn:exportClockingsByDateForEmployeeList",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult<ArrayOfClocking>> exportClockingsByDateForEmployeeListAsync(final ArrayOfAskedEmployee employeeList)
    {
        return executeAsync(new Functions.IFunc<ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return exportClockingsByDateForEmployeeList( employeeList);
            }
        },"exportClockingsByDateForEmployeeList");
    }
    
    
    
    public ArrayOfClocking exportClockingsByDate(final String populationFilter, final String groupFilter, final java.util.Date startDate, final java.util.Date endDate) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "exportClockingsByDate");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="populationFilter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(populationFilter!=null?populationFilter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="groupFilter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(groupFilter!=null?groupFilter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="startDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(startDate!=null? ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDate(startDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="endDate";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(endDate!=null? ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDate(endDate):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"exportedClockings",__envelope);
            }
        },"urn:exportClockingsByDate",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult<ArrayOfClocking>> exportClockingsByDateAsync(final String populationFilter, final String groupFilter, final java.util.Date startDate, final java.util.Date endDate)
    {
        return executeAsync(new Functions.IFunc<ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return exportClockingsByDate( populationFilter,groupFilter,startDate,endDate);
            }
        },"exportClockingsByDate");
    }
    
    
    
    public ArrayOfClocking exportClockings(final ArrayOfAskedPopulationWithPeriod employeeList) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://echange.service.open.bodet.com","employeeList", ArrayOfAskedPopulationWithPeriod.class);
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "exportClockings");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="employeeList";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(employeeList!=null?employeeList:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"exportedClockings",__envelope);
            }
        },"urn:exportClockings",__profile);
    }
    
    
    
    public android.os.AsyncTask< Void, Void, OperationResult<ArrayOfClocking>> exportClockingsAsync(final ArrayOfAskedPopulationWithPeriod employeeList)
    {
        return executeAsync(new Functions.IFunc<ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return exportClockings( employeeList);
            }
        },"exportClockings");
    }


    public ArrayOfClocking importClockings(final ArrayOfClocking clockingsToImport) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://echange.service.open.bodet.com","clockingsToImport",ArrayOfClocking.class);
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "importClockings");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="clockingsToImport";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(clockingsToImport!=null?clockingsToImport:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"clockingsInError",__envelope);
            }
        },"urn:importClockings",__profile);
    }



    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfClocking>> importClockingsAsync(final ArrayOfClocking clockingsToImport)
    {
        return executeAsync(new Functions.IFunc< ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return importClockings( clockingsToImport);
            }
        },"importClockings");
    }



    public ArrayOfClocking importPhysicalClockings(final ArrayOfClocking clockingsToImport) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfClocking)execute(new AGSIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://echange.service.open.bodet.com","clockingsToImport",ArrayOfClocking.class);
                SoapObject __soapReq = new SoapObject("http://echange.service.open.bodet.com", "importPhysicalClockings");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://echange.service.open.bodet.com";
                __info.name="clockingsToImport";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(clockingsToImport!=null?clockingsToImport:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (ArrayOfClocking)getResult(ArrayOfClocking.class,__result,"clockingsInError",__envelope);
            }
        },"urn:importPhysicalClockings",__profile);
    }



    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfClocking>> importPhysicalClockingsAsync(final ArrayOfClocking clockingsToImport)
    {
        return executeAsync(new Functions.IFunc< ArrayOfClocking>() {
            public ArrayOfClocking Func() throws java.lang.Exception {
                return importPhysicalClockings( clockingsToImport);
            }
        },"importPhysicalClockings");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public String deletePhysicalClockings(final String clockingsToDelete) throws java.lang.Exception
    {
        
/*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    
    
    public android.os.AsyncTask< Void, Void, OperationResult< String>> deletePhysicalClockingsAsync(final String clockingsToDelete)
    {
        return executeAsync(new Functions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return deletePhysicalClockings( clockingsToDelete);
            }
        },"deletePhysicalClockings");
    }

    protected java.lang.Object execute(AGSIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }

    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.setMethodName(methodName);
                    result.setResult(func.Func());
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.setException(ex);
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault, ExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
                
        if(fault.detail!=null && fault.detail.getChildCount()>0)
        {
            Element detailsNode=(Element)fault.detail.getChild(0);
            try
            {
                SoapObject exceptionObject = null;
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://echange.service.open.bodet.com","Exception");
                if (exceptionObject != null)
                {
                    Exception ex=new Exception();
                    ex.loadFromSoap(exceptionObject,envelope);
                    newException = ex;
                }
            }
            catch (java.lang.Exception e)
            {
                e.printStackTrace();
            }
            newException.detail=fault.detail;
            newException.faultactor=fault.faultactor;
            newException.faultcode=fault.faultcode;
            newException.faultstring=fault.faultstring;
            newException.version=fault.version;
        }
        return newException;
    }
}


