package com.kelio.webservice;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class EmployeeInformation extends Object implements KvmSerializable
{

    
    private Integer employeeKey;
    
    private String employeeSurname;
    
    private String employeeFirstName;
    
    private String employeeIdentificationCode;
    
    private String employeeBadgeCode;
    
    private String employeeIdentificationNumber;
    
    private Boolean archivedEmployee;
    
    public Integer getEmployeeKey()
    {
        return this.employeeKey;
    }
    
    public void setEmployeeKey(Integer value)
    {
        this.employeeKey = value;     
    }
    
    public String getEmployeeSurname()
    {
        return this.employeeSurname;
    }
    
    public void setEmployeeSurname(String value)
    {
        this.employeeSurname = value;     
    }
    
    public String getEmployeeFirstName()
    {
        return this.employeeFirstName;
    }
    
    public void setEmployeeFirstName(String value)
    {
        this.employeeFirstName = value;     
    }
    
    public String getEmployeeIdentificationCode()
    {
        return this.employeeIdentificationCode;
    }
    
    public void setEmployeeIdentificationCode(String value)
    {
        this.employeeIdentificationCode = value;     
    }
    
    public String getEmployeeBadgeCode()
    {
        return this.employeeBadgeCode;
    }
    
    public void setEmployeeBadgeCode(String value)
    {
        this.employeeBadgeCode = value;     
    }
    
    public String getEmployeeIdentificationNumber()
    {
        return this.employeeIdentificationNumber;
    }
    
    public void setEmployeeIdentificationNumber(String value)
    {
        this.employeeIdentificationNumber = value;     
    }
    
    public Boolean getArchivedEmployee()
    {
        return this.archivedEmployee;
    }
    
    public void setArchivedEmployee(Boolean value)
    {
        this.archivedEmployee = value;     
    }


    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);



    }

    @Override
    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("employeeKey"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeKey = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.employeeKey = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("employeeSurname"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeSurname = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeSurname = (String)obj;
                }
                else{
                    this.employeeSurname = "";
                }
            }
            return true;
        }
        if (info.name.equals("employeeFirstName"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeFirstName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeFirstName = (String)obj;
                }
                else{
                    this.employeeFirstName = "";
                }
            }
            return true;
        }
        if (info.name.equals("employeeIdentificationCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeIdentificationCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeIdentificationCode = (String)obj;
                }
                else{
                    this.employeeIdentificationCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("employeeBadgeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeBadgeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeBadgeCode = (String)obj;
                }
                else{
                    this.employeeBadgeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("employeeIdentificationNumber"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.employeeIdentificationNumber = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.employeeIdentificationNumber = (String)obj;
                }
                else{
                    this.employeeIdentificationNumber = "";
                }
            }
            return true;
        }
        if (info.name.equals("archivedEmployee"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.archivedEmployee = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.archivedEmployee = (Boolean)obj;
                }
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.employeeKey!=null?this.employeeKey:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+1)
        {
            return this.employeeSurname!=null?this.employeeSurname:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+2)
        {
            return this.employeeFirstName!=null?this.employeeFirstName:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+3)
        {
            return this.employeeIdentificationCode!=null?this.employeeIdentificationCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+4)
        {
            return this.employeeBadgeCode!=null?this.employeeBadgeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+5)
        {
            return this.employeeIdentificationNumber!=null?this.employeeIdentificationNumber:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==count+6)
        {
            return this.archivedEmployee!=null?this.archivedEmployee:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "employeeKey";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeSurname";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeFirstName";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeIdentificationCode";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeBadgeCode";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "employeeIdentificationNumber";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==count+6)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "archivedEmployee";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
