package com.kelio.webservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------





public interface IServiceEvents
{
    void Starting();
    void Completed(OperationResult result);
}
