package com.kelio.webservice;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Object extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String technicalString;
    
    private String errorMessage;
    
    public String getTechnicalString()
    {
        return this.technicalString;
    }
    
    public void setTechnicalString(String value)
    {
        this.technicalString = value;     
    }
    
    public String getErrorMessage()
    {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String value)
    {
        this.errorMessage = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info, SoapObject soapObject, ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("technicalString"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.technicalString = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.technicalString = (String)obj;
                }
                else{
                    this.technicalString = "";
                }
            }
            return true;
        }
        if (info.name.equals("errorMessage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.errorMessage = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.errorMessage = (String)obj;
                }
                else{
                    this.errorMessage = "";
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.technicalString!=null?this.technicalString:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.errorMessage!=null?this.errorMessage:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "technicalString";
            info.namespace= "http://echange.service.open.bodet.com";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "errorMessage";
            info.namespace= "http://echange.service.open.bodet.com";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
